version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: statify_postgres
    environment:
      POSTGRES_DB: statify
      POSTGRES_USER: statify_user
      POSTGRES_PASSWORD: statify_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statify_user -d statify"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: statify_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@statify.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
networks:

volumes:
  postgres_data:
  pgadmin_data: